version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: py
    versions:
    - 1.10.0
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
    - 2.12.1
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: flake8-bugbear
    versions:
    - 20.11.1
    - 21.3.1
    - 21.3.2
    - 21.4.3
  - dependency-name: isort
    versions:
    - 5.7.0
    - 5.8.0
  - dependency-name: flake8-comprehensions
    versions:
    - 3.3.1
    - 3.4.0
  - dependency-name: mypy
    versions:
    - "0.800"
    - "0.812"
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: flake8-debugger
    versions:
    - 4.0.0
  - dependency-name: flake8-print
    versions:
    - 4.0.0
  - dependency-name: flake8-eradicate
    versions:
    - 1.0.0
