exclude: '^$'
fail_fast: false
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['-r', '--in-place', '--remove-all-unused-imports']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
