exclude: '^$'
fail_fast: false
default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['-r', '--in-place',
               '--remove-all-unused-imports', '--ignore-init-module-imports']

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config
        args: ['--application-directories=src']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: ['-y']

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
