exclude: '^$'
fail_fast: false
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args: ['-r', '--in-place', '--remove-all-unused-imports']

  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
