FROM ghcr.io/ddoroshev/pybase:compile-3.11.4 as compile

COPY poetry.lock pyproject.toml /app/

RUN poetry install --no-root && poetry run pip install setuptools

COPY . /app/

FROM ghcr.io/ddoroshev/pybase:runtime-3.11.4 as runtime

COPY --from=compile /venv /venv
COPY --from=compile /app /app

CMD ["make", "test"]
